// Generated by scripts/stats-i18n.mjs from i18n/stats/*.po. Do not edit by
// hand: change the .po file and build, or run npm run stats-i18n.

import type { StatsLanguage } from './i18n.js'

export const STATS_TRANSLATIONS: readonly StatsLanguage[] = [
  {
    "tag": "tr",
    "phrases": {
      "title": "İnceleme istatistikleri",
      "generated": "oluşturuldu",
      "rangeTo": "–",
      "noneYet": "Henüz tamamlanmış inceleme yok.",
      "submissions": "incelenen gönderi",
      "entries": "dizge",
      "flagged": "işaretlenen",
      "repaired": "otomatik düzeltilen",
      "turnaround": "ortanca süre",
      "weeklyHeading": "Haftalara göre incelenen dizgeler",
      "peak": "en yüksek",
      "donutHeading": "Neler işaretleniyor",
      "projectHeading": "Projeye göre",
      "colProject": "Proje",
      "colSubmissions": "Gönderi",
      "colEntries": "Dizge",
      "colFlagged": "İşaretlenen",
      "colRate": "Oran",
      "emptyBody": "Henüz tamamlanmış inceleme kaydı yok. Bir gönderiyi incelediğinizde toplamları burada görünür.",
      "caveat": "“İşaretlenen”, polyglots’un bir insanın bakması için öne çıkardığı dizgeleri sayar; bunlar hem mekanik hatalar hem de yorum gerektiren durumlardır. Bu sayı, aracın neyi işaretlediğini ölçer; kimsenin emeğinin kalitesini değil. Bir işaret, gönderiyi yapan katkıcı hakkında bir yargı değildir.",
      "incompleteOne": "inceleme tamamlanmadı ve bu toplamlara katkı vermedi.",
      "incompleteMany": "inceleme tamamlanmadı ve bu toplamlara katkı vermedi.",
      "translateHeading": "Çeviri",
      "translateWeekly": "Haftalara göre çevrilen dizgeler",
      "runs": "çalıştırma",
      "drafted": "çevrilen dizge",
      "leftFuzzy": "bulanık bırakılan",
      "skippedEntries": "motorun atladığı",
      "engineHeading": "Motora göre",
      "colEngine": "Motor",
      "colRuns": "Çalıştırma",
      "colMedian": "Ortanca",
      "translateCaveat": "“Bulanık bırakılan”, yayına girmeden önce bir insanın denetlemesi için işaretlenen taslakları sayar. Taslak motorunun ve onun incelemesinin emin olamadığı yerlerdir; hata sayısı değildir.",
      "durationSeconds": "{n} sn",
      "durationMinutes": "{n} dk",
      "durationHours": "{n} saat",
      "theme": "Tema",
      "themeAuto": "Otomatik",
      "themeLight": "Açık",
      "themeDark": "Koyu"
    }
  }
]
