#!/usr/bin/env node
// Embeds the stats page translations from i18n/stats/*.po into the committed
// src/stats/translations-data.ts, before every build.
//
// The page is one HTML file with no script and no outside resource, so its
// strings cannot be looked up at run time from a file beside the binary: they
// have to be in the code that writes the page. Generating that code from .po
// files keeps the translator's side ordinary gettext, which is what every
// locale team already works in.
//
// Each translation is checked against the template rather than taken whole. A
// string whose English changed since it was translated would otherwise show the
// old meaning in another language, and English is the better fallback: it is
// what the page says when a language has no string at all.
//
// Unlike update-locales this fails closed. The inputs are files in this repo,
// so a .po that does not parse is a mistake to fix, not weather to wait out.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import gettextParser from 'gettext-parser'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const DIR = join(ROOT, 'i18n', 'stats')
const OUT = join(ROOT, 'src', 'stats', 'translations-data.ts')

// The tag lands in a lang attribute, a class name and a CSS selector, so it is
// held to the shape of a language tag rather than escaped three different ways.
const TAG = /^[a-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$/

function entries(text) {
  const parsed = gettextParser.po.parse(text)
  const out = []
  for (const [ctx, byId] of Object.entries(parsed.translations)) {
    for (const [id, entry] of Object.entries(byId)) {
      if (id === '') continue
      out.push({ ctx, id, str: entry.msgstr[0] ?? '', fuzzy: /\bfuzzy\b/.test(entry.comments?.flag ?? '') })
    }
  }
  return { headers: parsed.headers, entries: out }
}

/**
 * The translations each .po file contributes, keyed as in the template.
 * `files` are { name, text }; the language comes from the Language header, or
 * from the file name when the header is empty.
 */
export function embedTranslations(potText, files) {
  const english = new Map(entries(potText).entries.map((e) => [e.ctx, e.id]))
  const languages = files.map(({ name, text }) => {
    const po = entries(text)
    const tag = (po.headers.Language || name.replace(/\.po$/, '')).replace(/_/g, '-')
    if (!TAG.test(tag)) throw new Error(`${name}: "${tag}" is not a usable language tag; set the Language header`)
    const phrases = {}
    for (const e of po.entries) {
      if (e.fuzzy || e.str === '' || english.get(e.ctx) !== e.id) continue
      phrases[e.ctx] = e.str
    }
    return { tag, phrases }
  })
  return languages.sort((a, b) => a.tag.localeCompare(b.tag))
}

export function render(languages) {
  return `// Generated by scripts/stats-i18n.mjs from i18n/stats/*.po. Do not edit by
// hand: change the .po file and build, or run npm run stats-i18n.

import type { StatsLanguage } from './i18n.js'

export const STATS_TRANSLATIONS: readonly StatsLanguage[] = ${JSON.stringify(languages, null, 2)}
`
}

function main() {
  const names = readdirSync(DIR).filter((n) => n.endsWith('.po')).sort()
  const files = names.map((name) => ({ name, text: readFileSync(join(DIR, name), 'utf8') }))
  const languages = embedTranslations(readFileSync(join(DIR, 'stats.pot'), 'utf8'), files)
  const next = render(languages)
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {}
  const summary = languages.map((l) => `${l.tag} ${Object.keys(l.phrases).length}`).join(', ') || 'none'
  if (current === next) {
    console.log(`stats-i18n: ${summary}, unchanged`)
    return
  }
  writeFileSync(OUT, next)
  console.log(`stats-i18n: wrote ${summary} to src/stats/translations-data.ts`)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main()
