#!/usr/bin/env node
// Bundles the stats page's browser code (src/stats/page/entry.ts and what it
// imports) into the committed src/stats/client-bundle.ts, as one string.
//
// The page loads nothing from outside, so its script is inlined into every
// copy: the server's and the standalone file. TypeScript cannot produce that
// single file on its own (version 7 has no outFile), and the view code is
// shared with the server, so a bundler it is. The output is committed, like
// translations-data.ts, so a published package never needs esbuild at run
// time; a test fails when it is stale.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const ENTRY = join(ROOT, 'src', 'stats', 'page', 'entry.ts')
const OUT = join(ROOT, 'src', 'stats', 'client-bundle.ts')

export async function bundleClient() {
  const result = await build({
    entryPoints: [ENTRY],
    bundle: true,
    write: false,
    format: 'iife',
    platform: 'browser',
    target: 'es2022',
    minify: true,
    legalComments: 'none',
    charset: 'utf8',
    logLevel: 'silent',
  })
  return result.outputFiles[0].text.trimEnd()
}

export function renderBundleModule(code) {
  return `// Generated by scripts/stats-client.mjs from src/stats/page. Do not edit by
// hand: change the page code and run npm run stats-client.

export const CLIENT_JS = ${JSON.stringify(code)}
`
}

async function main() {
  const next = renderBundleModule(await bundleClient())
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {}
  if (current === next) {
    console.log('stats-client: unchanged')
    return
  }
  writeFileSync(OUT, next)
  console.log(`stats-client: wrote ${Math.round(next.length / 1024)} KB to src/stats/client-bundle.ts`)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await main()
