#!/usr/bin/env node
// Refreshes src/wporg/locales-data.ts from translate.wordpress.org/stats/, the
// one page that lists every locale with the WordPress code, the GlotPress slug
// and the translation set side by side.
//
// The mapping cannot be computed. nl_NL is "nl" but nl_BE is "nl-be"; pt_PT is
// "pt" but pt_AO is "pt-ao"; ca_valencia is "ca-val"; nl_NL_formal is the set
// "formal" of "nl", not a slug of its own. GlotPress keeps it as a table, so
// this does too.
//
// Run on purpose, with npm run update-locales, and the result committed. It
// used to run before every build and from prepare, which made every install
// from git and every publish depend on wp.org answering, and could ship a
// table that changed underneath a release with nobody looking at the diff.
//
// Fails open. Offline, or with wp.org changed so nothing parses, it keeps the
// committed table and says so, and the previous table is right for every
// locale it lists.

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const STATS_URL = 'https://translate.wordpress.org/stats/'
const OUT = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'wporg', 'locales-data.ts')
// Fewer rows than this means the page changed shape, not that locales vanished.
const MIN_LOCALES = 100

/** Each row's first locale link: its text is the WordPress code, its path the slug and set. */
export function parseStats(html) {
  const byCode = new Map()
  for (const row of html.matchAll(/<tr\b[^>]*>([\s\S]*?)<\/tr>/g)) {
    const link = /href="\/locale\/([^/"]+)\/([^/"]+)\/"[^>]*>([\s\S]*?)<\/a>/.exec(row[1])
    if (!link) continue
    const wp = link[3].replace(/<[^>]+>/g, '').trim()
    if (!/^[a-z]{2,3}(?:_[A-Za-z0-9]+)*$/.test(wp)) continue
    byCode.set(wp, { wp, slug: link[1], set: link[2] })
  }
  return [...byCode.values()].sort((a, b) => a.wp.localeCompare(b.wp))
}

export function render(locales, fetchedOn) {
  const rows = locales.map((l) => `  { wp: '${l.wp}', slug: '${l.slug}', set: '${l.set}' },`).join('\n')
  return `// Generated by scripts/update-locales.mjs from ${STATS_URL} on ${fetchedOn}.
// Do not edit by hand: npm run update-locales rewrites it. Committed so builds and
// tests are reproducible offline.

export interface WporgLocaleRow {
  // The WordPress locale code, as in wp-config.php: nl_NL, nl_NL_formal.
  wp: string
  // The GlotPress locale slug used in translate.wordpress.org paths: nl, nl-be.
  slug: string
  // The translation set: default, or a variant such as formal or ao90.
  set: string
}

export const WPORG_LOCALES: readonly WporgLocaleRow[] = [
${rows}
]
`
}

async function main() {
  let locales
  try {
    const res = await fetch(STATS_URL, { headers: { 'User-Agent': 'polyglots build (+https://github.com/emreerkan/polyglots)' } })
    if (!res.ok) throw new Error(`answered ${res.status}`)
    locales = parseStats(await res.text())
    if (locales.length < MIN_LOCALES) throw new Error(`only ${locales.length} locales parsed; the page may have changed`)
  } catch (err) {
    console.warn(`update-locales: kept the committed table (${err instanceof Error ? err.message : err})`)
    return
  }
  const next = render(locales, new Date().toISOString().slice(0, 10))
  let current = ''
  try {
    current = readFileSync(OUT, 'utf8')
  } catch {}
  // Compared without the date line, so an unchanged table is not rewritten
  // every day and the working tree stays clean.
  const body = (s) => s.split('\n').slice(1).join('\n')
  if (body(current) === body(next)) {
    console.log(`update-locales: ${locales.length} locales, unchanged`)
    return
  }
  writeFileSync(OUT, next)
  console.log(`update-locales: wrote ${locales.length} locales to src/wporg/locales-data.ts`)
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) await main()
